ci: added gather job

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: Checks and Validation
+name: Build Packages
 on:
   pull_request:
   push:
@@ -72,3 +72,22 @@ jobs:
           nix_path: nixpkgs=channel:nixos-unstable
       - name: Dummy build step
         run: echo Building package ${{ matrix.package }}...
+
+  build-gather:
+    needs:
+      - prepare-build
+      - build
+    name: Gather Build Results
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Output build results
+        run: |
+          RESULT="${{ needs.build.result }}"
+          if [ $RESULT == "success" || $RESULT == "skipped" ]; then
+            echo "Build succeeded for all packages"
+            exit 0
+          else
+            echo "Build failed for one or more packages"
+            exit 1
+          fi
